name = "little-mouse-7c21"
main = "src/axiom.js"
compatibility_date = "2023-08-23"

[placement]
mode = "smart"

routes = [
  { pattern = "wedding.launi.me/*", zone_name = "launi.me" }
]

[vars]
AXIOM_DATASET = "wedding-launi-me-dev"
